# This configuration file should contain all required configuration parameters
# for the ingest workflow to run with additional Nextstrain automation rules.

# Custom rules to run as part of the Nextstrain automated workflow
# The paths should be relative to the ingest directory.
custom_rules:
  - build-configs/nextstrain-automation/upload.smk

# Nextstrain CloudFront domain to ensure that we invalidate CloudFront after the S3 uploads
# This is required as long as we are using the AWS CLI for uploads
cloudfront_domain: "data.nextstrain.org"

# Nextstrain AWS S3 Bucket with pathogen prefix
s3_dst: "s3://nextstrain-data/files/workflows/dengue"

# Mapping of files to upload
files_to_upload:
  genbank.ndjson.xz: data/genbank.ndjson
  all_sequences.ndjson.xz: data/sequences.ndjson
  metadata_all.tsv.zst: results/metadata_all.tsv
  sequences_all.fasta.zst: results/sequences_all.fasta
  metadata_denv1.tsv.zst: results/metadata_denv1.tsv
  sequences_denv1.fasta.zst: results/sequences_denv1.fasta
  metadata_denv2.tsv.zst: results/metadata_denv2.tsv
  sequences_denv2.fasta.zst: results/sequences_denv2.fasta
  metadata_denv3.tsv.zst: results/metadata_denv3.tsv
  sequences_denv3.fasta.zst: results/sequences_denv3.fasta
  metadata_denv4.tsv.zst: results/metadata_denv4.tsv
  sequences_denv4.fasta.zst: results/sequences_denv4.fasta
